---
# tasks file for prometheus-client

# Check for current node_exporter install

- name: check if node_exporter exists
  stat:
    path: "{{ node_exporter_bin }}"
  register: __node_exporter

# Prep system for node_exporter

- name: create node exporter user
  user:
    name: "{{ node_exporter_user }}"
    append: true
    shell: /usr/sbin/nologin
    system: true
    create_home: false

- name: create node exporter config dir
  file:
    path: "{{ node_exporter_dir_conf }}"
    state: directory
    owner: "{{ node_exporter_user }}"
    group: "{{ node_exporter_group }}"


#Download and install node_exporter

- name: download and unzip node exporter if not exist
  unarchive:
    src: "{{ node_exporter_download_url }}"
    dest: /tmp/
    remote_src: yes
    validate_certs: no
  when: not __node_exporter.stat.exists

- name: move the binary to the final destination
  copy:
    src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter"
    dest: "{{ node_exporter_bin }}"
    owner: "{{ node_exporter_user }}"
    group: "{{ node_exporter_group }}"
    mode: 0755
    remote_src: yes
  when: not __node_exporter.stat.exists

- name: clean
  file:
    path: /tmp/node_exporter-{{ node_exporter_version }}.linux-amd64/
    state: absent


#Install and start node_exporter service

- name: install service
  template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    owner: root
    group: root
    mode: 0755
  notify: reload_daemon_and_restart_node_exporter
